name: Create the PDF

on:
  push:
    paths:
      - 'docs/**'
      - .github/workflows/create_pdf.yaml
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: See the PDF is there
        run: ls docs/paper.pdf

      - name: Delete the PDF
        run: rm docs/paper.pdf

      - name: See PDFs are gone
        run: ls docs/paper.pdf

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install pdflatex
        run: sudo apt-get install texlive-latex-base texlive-latex-recommended

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Install libharfbuzz-dev libfribidi-dev
        run: sudo apt install -qq libharfbuzz-dev libfribidi-dev

      - name: Install libfontconfig1-dev
        run: sudo apt install -qq libfontconfig1-dev

      - name: Install devtools
        run: install.packages("devtools")
        shell: Rscript {0}

      - name: Install devtools
        run: install.packages("remotes")
        shell: Rscript {0}

      - name: Install mkdocs2md
        run: remotes::install_github("richelbilderbeek/mkdocs2md")
        shell: Rscript {0}

      - name: Create PDF
        run: |
          ./scripts/create_pdf.sh
          mv build/paper.pdf docs

      - name: Upload books
        uses: actions/upload-artifact@v4
        with:
          name: paper.zip
          path: docs/paper.pdf
